### ISSUE TITLE
Split-up tests in ReadOnly vs ReadWrite on qiita_db

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1029]
I'm listing everything here, just in case that somebody wants to work in something that requires no brain. Please submit a PR per single file. Add your name next to the file that you're currently working in.
This will reduce development time since tests are run faster.

Some general rules
 - If the code tested potentially modifies the database, it should go under the ReadWrite category, in case that the code is not working correctly it does not impact other tests
 - If both tests sets are going to share a lot of data, useful to create a single base class that initializes both test classes. 

 - [ ] qiita_db/test/test_analysis.py
 - [x] qiita_db/test/test_artifact.py (Jose)
 - [ ] qiita_db/test/test_base.py
 - [ ] qiita_db/test/test_commands.py
 - [ ] qiita_db/test/test_data.py
 - [ ] qiita_db/test/test_job.py
 - [ ] qiita_db/test/test_logger.py
 - [ ] qiita_db/test/test_meta_util.py
 - [x] qiita_db/test/test_metadata_template.py (Jose - PR #1033)
 - [ ] qiita_db/test/test_ontology.py
 - [ ] qiita_db/test/test_parameters.py
 - [x] qiita_db/test/test_processing_job.py (Jose)
 - [ ] qiita_db/test/test_reference.py
 - [ ] qiita_db/test/test_search.py
 - [ ] qiita_db/test/test_setup.py
 - [x] qiita_db/test/test_software.py (Jose)
 - [ ] qiita_db/test/test_sql.py
 - [ ] qiita_db/test/test_sql_connection.py
 - [ ] qiita_db/test/test_study.py
 - [ ] qiita_db/test/test_user.py
 - [ ] qiita_db/test/test_util.py

**Comment by souravsingh** [comment]
I would like to work on this issue.How do I start?

**Comment by antgonza** [comment]
@souravsingh that will be great, thanks!

Some background: currently we working on improving the time it takes to run the qiita tests as it is slowly becoming an issue and this is one of the likely culprits. Basically, every time that we run the DB tests we are resetting the database to a fresh install. To facilitate this task we decided to create a decorator, used [here](https://github.com/biocore/qiita/blob/master/qiita_db/test/test_analysis.py#L28), to do this operation at the end of each test. Also, we have this decorator even in those cases were we are only querying the DB (AKA we don't need to reset).

This issue is basically going over the list of test files and splitting them, within each file in 2 sections, those that are actually changing the DB (need reset) and those that are simply querying it. [Here](https://github.com/biocore/qiita/pull/1033/files) an example of what needs to be done.

**Comment by josenavas** [comment]
@souravsingh Thanks for helping! Let us know if you face any trouble getting started. I would suggest also adding your name next to the file that you're working on, so we avoid duplication of effort. I tackled a couple of more files in here because I need to fix them for an ongoing PR.

**Comment by antgonza** [comment]
Closing this as we have changed the way tests are being run and now this is obsolete. For more information see: https://github.com/biocore/qiita/pull/1927
