### ISSUE TITLE
Start using the AJAX POST capabilities 

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1036]
Currently a lot of the javascript form submissions work by building a form in the DOM and submitting it. We should be leveraging jQuery or AJAX post capability to send the information instead.

**Comment by ElDeveloper** [comment]
:+1:, any ideas of what milestone should this issue belong to?

**Comment by josenavas** [comment]
I would suggest adding it to Alpha 0.2, so we can enforce it before we are adding more and more functionality

**Comment by josenavas** [comment]
Forgot to add: alpha 0.2 with lowest priority, so if it doesn't make it, is not a big deal

**Comment by adamrp** [comment]
@squirrelo I had suggested this in a previous comment
<https://github.com/biocore/qiita/pull/569#discussion_r20044572>, but as I
recall you tried to implement it that way and it didn't work. I no longer
recall why it was posing difficulties, though; is this ringing any bells?

**Comment by josenavas** [comment]
I was trying to remember the issue and now I do! Sometime we need to update the displayed page. In those case, using jquery does not work, as you cannot modify the current page without either duplicating a lot of code, o doing a lot of nasty tricks... I guess it depends on what we need to do, we should use jquery+ajax and in others use ajax...

**Comment by adamrp** [comment]
I'm pretty sure using jquery+ajax is the same as using ajax alone, just
more convenient (at least syntactically).

**Comment by josenavas** [comment]
Sorry, what I meant is to use jquery+ajax (or just ajax) vs DOM.... Thanks for the catch @adamrp

**Comment by adamrp** [comment]
Ah! Okay, thanks for clarifying. However, in this case, I believe what @squirrelo was referring to is just replacing the javascript functions that we are using to generate forms (e..g, [these lines](https://github.com/biocore/qiita/blob/master/qiita_pet/templates/study_description.html#L415-L431)) with [jquery post](https://api.jquery.com/jquery.post/), passing the relevant information in the data argument (please correct me if I'm misinterpreting this issue).

I *think* @squirrelo tried this before, but it didn't work for some reason.... Although I thought it would work if the AJAX callback updated the DOM. Anyways, this is a low priority change that presented challenges in the past, so probably not worth spending time right now given the planned alpha releases coming up. I would personally move this to beta, since I don't think it is urgent to implement this by the end of the month (when alpha 0.2 is planned for release).

**Comment by josenavas** [comment]
Yeah, I agree with you. The person that wants to explore this should take 1 function, try multiple potential solutions and post here the results, so we no longer ask this again.

**Comment by squirrelo** [comment]
I tried it earlier but it boiled down to not having the knowledge to do so, mostly due to the async nature of ajax. I think it's doable now that we've all had some experience with this type of setup.

**Comment by antgonza** [comment]
Group resolution: all new code was written using this idea, old code shouldn't be updated (if working, why change?), and all new code should use it. Thus, closing.
