### ISSUE TITLE
Use glowing dangerzone package for SQL connections

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1037]
The micropackage needs updating, and then we can use it here. Alternately, it was discussed that we might have everything needing the sql_connection.py be dependent on qiita to get that file.

**Comment by josenavas** [comment]
I was thinking that one of the main problems that we have is that we are not using all the SQL capabilities to do some of the work; and we are implementing python "wrappers/extensions" in order to do that. I would like to double check that we actually need that many changes in the GD package or we actually need to change the way we are doing SQL. Also, IMOO, i we at least want to avoid code duplication, we should check the differences between the 2 files, update GD to be equal as the Qiita one, and then just replace imports.

**Comment by josenavas** [comment]
Actually, thinking a bit more, we should update both files to look equal, and then drop glowing dangerzone, porting the issues here. The main motivation for this is that both projects are in pre-alpha, which is less than ideal for development.

**Comment by antgonza** [comment]
Can we close this one?

**Comment by antgonza** [comment]
Closing cause that package doesn't even exist anymore, it was merged to qiita.
