### ISSUE TITLE
Modify EBI code so that it does not upload empty files

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1070]
These cause error messages to be thrown from EBI's end

**Comment by adamrp** [comment]
I think this should be Alpha 0.2. It is a time sink for Gail because she has to run demux once, look at the log, manually remove samples with zero sequences from the prep template, and run demux again.

**Comment by josenavas** [comment]
@adamrp Are you able to work on this?

**Comment by rob-knight** [comment]
+1

On May 7, 2015, at 10:22 AM, adamrp <notifications@github.com> wrote:

I think this should be Alpha 0.2. It is a time sink for Gail because she
has to run demux once, look at the log, manually remove samples with zero
sequences from the prep template, and run demux again.

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1070#issuecomment-99943542>.

**Comment by adamrp** [comment]
Yes, I think I can do this later today

**Comment by josenavas** [comment]
Thanks! assigning to you so we don't loose track :-)
