### ISSUE TITLE
should study.exists check by id?

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1078]
Currently you instantiate a study by `Study(id_)` but you check if a study exists by `Study.exists(study_title)`, which is confusing. What we want to do? Everything by id_, study_title or both (exists_by_id).

**Comment by josenavas** [comment]
My vote goes to both, because we have said that cannot be duplicate study titles on the DB.

**Comment by wasade** [comment]
Could we just get rid of the ID then? If the study title is a natural
primary key then there isn't a need for both, right?

**Comment by antgonza** [comment]
Not sure. I agree on the idea but in practice having FKs to the full
name might not be ideal. BTW having unique names is great!

**Comment by squirrelo** [comment]
I agree unique names are great. For this issue, however, if you look at Job and Reference objects you see that exists should never take an ID. What exists does is check, given the data it takes in, whether something already exists with that data. This Study exists is consistent with that philosophy.

**Comment by josenavas** [comment]
That is a great point @squirrelo 
The exist was used to avoid data duplicates in the DB, e.g. avoid running 2 jobs that have been applied with the same options on the same data; similarly it is used to avoid 2 studies with the same name. In some other cases, like RawData is tricky to use, probably we can use md5 sums to check if it exists or not.

That being said, I think the current implementation follows the expected behavior and this is correct. If any function needs to check for the `id`, it can use the private function [`_check_id`](https://github.com/biocore/qiita/blob/master/qiita_db/base.py#L116) implemented in the base class.

**Comment by antgonza** [comment]
Closing as it seems that we agree that the current implementation is fine.
