### ISSUE TITLE
Allow uploading a processed data (BIOM)

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1085]
Users should be able to upload a processed data (BIOM tables) to use in their meta-analysis. This requires:
  - Check if the sample ids in the BIOM table correspond to the IDs in the DB
  - Modify the UI interface to support this (the back end already supports this once the previous point is solved)
  - Modify study listing page to check if it has processing information or not.

**Comment by adamrp** [comment]
See relevant discussion on this in #1161

**Comment by adamrp** [comment]
@biocore/qiita-dev I think this issue is bigger than I (or others) originally realized, and I won't be able to get this done for this Saturday. I have to shift focus to other priorities. I pulled @josenavas's branch (fix-1084) and have been working off of that in [my own branch](https://github.com/adamrp/qiita/tree/upload_biom-issue-1085), where I have made significant progress.

**Comment by josenavas** [comment]
@adamrp assigning to you as you're already working on this

**Comment by antgonza** [comment]
Update on this issue, currently you can upload a biom table but it's not validated (run prefix or sample name matches the names in the biom). Additionally, no processing commands are shown.
