### ISSUE TITLE
We show all users on the system, which is probably not good

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1092]
Discovered when using lynx on qiita.microbio.me. If you navigate to view my studies, you see a list of all users that have accounts on qiita. Not sure why, seems... not good.

**Comment by antgonza** [comment]
My guess is that JS/jquery is not working well and is showing all the
emails (not all info) as it is used for the display of studies. Not
sure if there is a work around this.

**Comment by squirrelo** [comment]
This is a byproduct of the sharing code autocomplete feature. Do we want to remove the autocomplete and instead have them type in the full email, then give a yes/no indication on the user existing and sharing working?

**Comment by wasade** [comment]
I think its low prio right now, but websockets?

**Comment by wasade** [comment]
What method does google use when typing in a search bar?

**Comment by squirrelo** [comment]
I don't know, but we apparently may be able to ajax this:
https://rvieiraweb.wordpress.com/2013/04/20/jquery-ajax-chosen-simple-demo-tutorial/

**Comment by josenavas** [comment]
This is going to be slow unless we cache those values at some place, so we don't have to go to the database that many times.

**Comment by ElDeveloper** [comment]
Redis to the rescue :D!

**Comment by squirrelo** [comment]
While looking into #1730 I realized this is still open. I want to close this as part of the share changes, but there is one sticking point: Do we want to keep the autocomplete functionality at all? It looks to me like it would be just as not good, since someone could easily type 'a', get all emails, then 'b', get all emails, etc and quickly have the emails of everyone on the system.

The safer way is to have a text box for entering a user email that, when you hit share, says 'successful' or 'user does not exist' depending on the outcome. This removes the security concern completely, and presumably you would have the email of your collaborator you are sharing a study with.

There are ways to make redis autocomplete happen (http://stackoverflow.com/a/24425711 and https://www.devbridge.com/sourcery/components/jquery-autocomplete/#) but I would like people's input before going that route.

**Comment by ackermag** [comment]
Not sure why we would hide users.

**Comment by squirrelo** [comment]
The major concern is that anyone with an account on the system would be able to access everyone else’s email address, opening users up to spamming.

**Comment by rob-knight** [comment]
This seems like a theoretical rather than practical concern surely?

**Comment by antgonza** [comment]
Agree with @rob-knight comment, it's possible but not sure if it will actually happen. My suggestion will be not to reduce functionality ... should we close this issue?

**Comment by squirrelo** [comment]
This issue deals with the fact that emails are directly in the HTML we send, which is really bad for security. I'm moving all autocomplete calculations server-side to fix this issue, so it is still open.

**Comment by antgonza** [comment]
OK, thanks.
