### ISSUE TITLE
Custom parameters on BIOM table

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1161]
When users upload a BIOM table, they should be able to indicate what parameters were used to process the BIOM table, in the case where this parameters are not available in the database, should the new parameters be added to the database by the user? The downside to this is that those parameters would become available for users to process new sequences, is this OK or do we want to keep this separate?

Related to #1085.

**Comment by adamrp** [comment]
When we discussed this previously, we decided that we were going to provide and curate the processing parameters that users could use to process (or preprocess, for that matter) their data. I think allowing the parameter sets to be added to the database by arbitrary users circumvents this regulation.

IMHO, users should be able to upload their biom tables for comparison with other data in Qiita, but such data should only be sandbox. This would provide a convenient way for users to look at their data in the context of other studies and data in Qiita, but we would maintain the standardization of processing parameters for studies that we curate (i.e., public and private studies).

**Comment by ElDeveloper** [comment]
> IMHO, users should be able to upload their biom tables for comparison with other data in Qiita, but such data should only be sandbox. This would provide a convenient way for users to look at their data in the context of other studies and data in Qiita, but we would maintain the standardization of processing parameters for studies that we curate (i.e., public and private studies).

You are correct, this is exactly what the different stages (sandboxed,
private, etc) allows users to do.

**Comment by josenavas** [comment]
We should be careful with this. Are we talking in terms of our own site or Qiita in general? Note the issues we had in the code sprint and the feedback that we got from @gregcaporaso . We want the system to be installed by the users and use it locally. In order to do that, the system should allow to add any arbitrary set of parameters. However, if we don't want this behavior in our system, we should put other mechanisms in place, limiting the general functionality, rather than limiting the entire system to our specific use case...

**Comment by adamrp** [comment]
@josenavas you are right. This is getting pretty complex, can we enumerate the actual use cases that we are trying to support?

1. **Single user, local installation**:  In this case, the fact that everything is "sandbox" does not matter, AFAIK
2. **Multi-user, "server" installation**: E.g., our deployment, the Broad's deployment, etc.
3. **Multi-user, local installation**: Is this *actually* a use case? I don't really know why one would want to do this.

Assuming (3) is not a use case we need to support, then I think (2) is the only place we need to worry about this, correct? If that's the case, and we are considering standardized processing a feature of Qiita (personally, I consider it one of the *main* features of Qiita, and highlight it in presentations), then I think keeping processed data that is uploaded directly (e.g., biom tables) as sandbox status makes sense.

**Comment by josenavas** [comment]
I would suggest that keeping them as 'sandbox' always is the way to go. If we think in the future that this is something that others need to control, it would be pretty straightforward to add it as a configuration parameter in the qiita_config.

Re: (3) I would suggest that the difference between (2) and (3) is that we're doing the installation on (2), while (3) can be some external lab setting up an internal server. Although these two options are virtually the same, the fact that somebody else can be doing this type of installation forces us to make these limitations easy to configure/install.

**Comment by adamrp** [comment]
Ok, I'll go ahead with that then. Thanks!

**Comment by adamrp** [comment]
How do we want to handle processed data that does not have processing parameters. Currently the `processed_data.create` function has two required arguments (`processed_params_table and `processed_params_id`). The easiest thing to do (code-wise) is to create a dummy table, e.g.,
```sql
CREATE TABLE processed_params_unknown (processed_params_id bigserial primary key, not_processed_in_qiita varchar not null default 'This data was not processed in Qiita');
INSERT INTO TABLE processed_params_unknown VALUES (DEFAULT);
```
This feels a little dirty, but would play nicely with existing code.

**Comment by josenavas** [comment]
I think this is actually the cleanest solution that we can do right now.

**Comment by adamrp** [comment]
Okay, next question: currently [these lines](https://github.com/biocore/qiita/blob/master/qiita_db/data.py#L1438-L1444) assume that all processed data have a reference associated. Should I have the user input what reference they used (this runs the risk of them lying or getting it wrong, of course) or should I add an "unknown reference" to the reference table?

Actually... thinking more about this, maybe it would be best to allow the user to fill out *all* the details of the processed data they are uploading (which parameter set they used, what reference they used, etc.), and just trust them to get it right. Since processed data uploaded in this way will remain sandboxed anyways, if they get it wrong, it's not really a problem... right?

**Comment by antgonza** [comment]
I'm not sure all biom tables should have a reference, for example: metabolomics. As they are sandboxed, should we simply allow to upload whatever? This means that for a meta-analysis they will only be able to mix uploaded biom tables.

**Comment by rob-knight** [comment]
That’s right, there are de novo approaches that don’t rely on a reference even to things like taxonomy.

**Comment by josenavas** [comment]
That is a bug and needs to be changed, since that is coupling the processed data to a target gene data type.

**Comment by adamrp** [comment]
Okay, that makes perfect sense and is in line with my initial intuition. Currently, on the study listings page, this information is assumed to exist:

![image](https://cloud.githubusercontent.com/assets/2574407/7873998/bde64186-0566-11e5-997b-6edd84f17b91.png)

ID: Automatically assigned
Data Type: getting from user upon upload
Processed Date: the time the file is uploaded
Algorithm: will be "unknown", [since the table is called "processed_params_unknown"](https://github.com/biocore/qiita/blob/master/qiita_db/data.py#L1463-L1464)
Reference: **Should I remove this from this display?**
Samples: This will be 0 [since this depends on the processed data having a prep template](https://github.com/biocore/qiita/blob/master/qiita_db/data.py#L1470-L1489)

It sounds like from these most recent comments that the "Reference" column should be removed.

As for Samples: should we require the user to link the processed data they are uploading to an existing prep template that they've uploaded?

**Comment by wasade** [comment]
What about "n/a", "de novo", or "no reference"?

Can't the number of samples be pulled from the uploaded table, mapping
file, or the intersection between the two?

**Comment by adamrp** [comment]
"n/a" sort of works, but if it is not going to be applicable to all processed data, should it really be there? 

I think that table on the study listings page could (should?) be cut down to just:
ID
Data Type
Processed Date
Samples

Samples would be good to have, but would have to be pulled from disk, which I don't care for since it would have to make assumptions about the file type. Currently it's pulled from the database (see last link in my previous comment). Having the user link the processed data they upload to an existing prep template *I think* would be easiest (and does make a certain amount of sense).

**Comment by adamrp** [comment]
And I think pulling the samples from the mapping file wouldn't be good here since the processed data might contain only a subset of the samples in the sample template

**Comment by wasade** [comment]
It's applicable to a lot of processed data though, including but not
limited to amplicon, metagenomic, and metatranscriptomic

**Comment by wasade** [comment]
Right, intersection then?

Aren't we fine with assumptions about the filetype or is more than just
biom being accepted? If classic and biom-format 1.0 are allowed for upload,
we could just do an implicit conversion so everything is biom-format 2.1 on
our end

**Comment by adamrp** [comment]
Re: going to disk to get the samples, I'll let others contribute their opinions, but I don't like it.

Re: reference, this information would still be available on the analysis page modal:
![image](https://cloud.githubusercontent.com/assets/2574407/7874305/03fcd866-056b-11e5-9bb5-2453d06d3c49.png)
but it complicates everything considerably to have it here also.

**Comment by adamrp** [comment]
Also, see discussion about related issue #1210 where this entire table (in its current form) is proposed to disappear from the study listing page

**Comment by antgonza** [comment]
@ElDeveloper, can we close this issue?

**Comment by ElDeveloper** [comment]
I think we can.
