### ISSUE TITLE
Better way to search/browse metadata categories

### ISSUE THREAD

**Issue by Shaunson26** [biocore/qiita#1190]
I think the way to search metadata categories could be improved. It is difficult to know what the available variables are for each metadata category. I propose that instead of having a search option, there should be a hierarchical browser tree that will also have the number of hits for each sub tree e.g
- env_matter:  
    ENVO:fresh water  250  
    ENVO:rhizosphere 300  
    ENVO:soil 350  
    ENVO:sterile water 5  
    ENVO:biofilm 2  
    ENVO:sea water 600

**Comment by josenavas** [comment]
Thanks @Shaunson26 !

This is going to be hard to implement as the system is right now, since this will mean that we have some notion of hierarchical information about the metadata. It can be accomplished with the Ontologies, but not with any arbitrary piece of metadata.

We will discuss this and try to come up with a good solution, specially for those metadata categories (e.g. `env_matter`) that actually hold that information.

**Comment by antgonza** [comment]
this is now available via redbiom and should be available in the next qiita deploy.
