### ISSUE TITLE
Status should be on prep_template_samples

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1215]
After discussion yesterday, we agreed that status should live in the prep template sample table, not on the processed data. This way we control access to samples straight at the sample level, for each processing run/different datatype. This can then percolate up through raw data, pre-processed data, etc as the statuses being the most restrictive of all samples in the file.

This ties in with #1193

**Comment by josenavas** [comment]
I don't agree with this. We should discuss this again in the next meeting. I've the feeling that there has been multiple things ignored in the decision of this solution.

**Comment by squirrelo** [comment]
What things specifically? There was along discussion on this.

**Comment by josenavas** [comment]
E.g. that the samples in the prep template cannot be extended, so no need on setting the status on a per samples basis...

**Comment by josenavas** [comment]
Also, note that the only issue is that we are showing samples from the SampleTemplate that should not be visible, not from the prep template. This can be easily achieved by just filtering the sample template when it is shown to the user. This has been already done recently with one issue in EBI, so not a lot of "new code" will need to be developed...

**Comment by adamrp** [comment]
The combination of (sample template, prep template) is one-to-one with a processed data, and also one-to-one with a mapping file. If we control public/private status at the prep_template_samples level, are we going to have two processed datas and two mapping files associated with each prep template (one that contains all the samples regardless of status, and one that contains only the public samples)? Sorry if I'm not remembering this being raised in the discussion on Weds.

**Comment by josenavas** [comment]
Good point @adamrp . Not only that, what I'm concerned right now, is that we can automatically control the status of a ProcessedData, which give us control of a single PrepTemplate (due to 1 - 1 relationships). If we move this control to the Sample level, the user will need to introduce this status for each sample, which I don't think it is something that we need to do.

Again, I think this whole discussion started because we are showing up the entire sample template, which can be easily solved by filtering the sample template visibility based on the PrepTemplates that the user can see...

**Comment by josenavas** [comment]
Outcomes from the discussion:

    * The status remain in the ProcessedData.
    * When a user wants to generate a new (Pre)processed data from a
      prep template/preprocessed data that is already public, the new data
      generated inherits the public status.

**Comment by antgonza** [comment]
@josenavas @squirrelo @adamrp, can we close this?
