### ISSUE TITLE
Refactor the generate_files and to_file functions

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1424]
The functions are horribly inefficient (By not sorting the dataframe and instead sorting in the SQL alone I was able to drop from 30ms to 10ms runtime) so these functions really need to be revisited. Also, once they are efficient we will no longer need to store the files, and instead can generate them on the fly removing the possibility of the files being out of sync with the database.

**Comment by adamrp** [comment]
Poking around in the code, it looks like `TRN` is used in a lot of places. Since `generate_files` and `to_file` functions are not going to modify the database, most of these seem unnecessary (e.g., [here](https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template/sample_template.py#L215) and [here](https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template/base_metadata_template.py#L974) and [here]). I doubt this is driving the cost of these functions up very much, but it's at least something.

As an aside, 30ms (or 10ms) doesn't seem that bad, since we're not running these functions thousands of times a day or anything. Is this really something that we need to prioritize optimizing? It seems to me that we could already generate them on the fly even with the the current code, no?

**Comment by squirrelo** [comment]
This was on our test database data, but w have larger studies where the increase could be even more significant. Also, with so small a change making such a large impact, it's better to look through and see if we can't get any more speed out of the function. We could probably get an order of magnitude or more with tweaks like that one and using pandas + SQL more intelligently.

**Comment by josenavas** [comment]
@adamrp those calls to `TRN` are needed to make sure that the entire function is executed as a transaction

**Comment by adamrp** [comment]
Right -- but they are read-only, right? So is the concern that the data could be modified by a different query/process halfway through the execution of the function?

**Comment by wasade** [comment]
Is this actually a performance burden that is impacting users? What is the
real world impact of this method? I think what @adamrp is getting at is the
potential to accidentally optimize something that is only a fraction of
runtime, in which case, multiple orders of magnitude wouldn't result in a
practical benefit. The downsides are increase code entropy and complexity.
If this is really is impacting people, then :+1:, otherwise, better to
leave be and focus elsewhere.

**Comment by josenavas** [comment]
Yes, is to avoid data modification through the execution of the function.

The performance discussion comes by making the users generate the files every time that they want to download, rather than just storing the files as we are doing right now...

**Comment by wasade** [comment]
@josenavas, not sure I understand your comment. Are you suggesting there _is_ a performance issue that is impacting people, or that there isn't? Or is this in reference to caching data for distribution?

**Comment by josenavas** [comment]
I think this is NOT a performance issue.

**Comment by wasade** [comment]
Okay, thanks

**Comment by squirrelo** [comment]
To clarify: We should be making the files on the fly instead of storing them, since that removes the possibility of the files being out of sync with the database, as said in the issue. There are also performance increases we can do to the file generation code that will facilitate this change, since it will be being called much more frequently when things are made on the fly.

**Comment by josenavas** [comment]
This requires some refactor that is not priority right now. There are other parts of the code that need to be refactored first.

**Comment by antgonza** [comment]
As a group on October 4th, 2017, we decided that we will not generate on the fly but that we need to rethink the creation of QIIME map files. Mainly, because if you update a sample, all preps have to be updated AKA AGP takes 20+ min.

**Comment by antgonza** [comment]
AFAIK this can be closed.
