### ISSUE TITLE
Server communication error on study list page

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1455]
If you open the study page and leave it open for a while you will get the "Server communication error. Sample selection will not be recorded. Please try again later.". If you refresh the page the message goes away. We should figure out how to avoid this happening.

Note that this didn't happen before, not sure if is something in the new hardware configuration.

cc: @clozupune

**Comment by josenavas** [comment]
@antgonza that is not completely correct. I've seen that issue happening mostly since we started using websockets.

The main problem is that the websocket closes (maybe due to a time-out). The solution will be to reopen it if it has been closed. Note that even doing that, there might be cases in which is not possible to re-open and the only solution is to re-load the page...

**Comment by antgonza** [comment]
closing for now as I haven't seen this happen in a long time, please reopen if otherwise.
