### ISSUE TITLE
allow emperor to plot unique values

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1465]
The issue is that some datasets (for example: the infant time series) the most interesting field has unique values in all rows. However, this feature is blocked by emperor. I can see two (3?) options: (1) We could open completely via emperor, (2) as part of showing the [summary of the biom table](https://github.com/biocore/qiita/issues/1296) we allow the user to select which categories to color by (then overwriting the not to color by unique values, which is the default in emperor), or (3) both.

cc - @rob-knight and @RNAer

**Comment by rob-knight** [comment]
(3) would be optimal but I realize it's more work...

On Sep 7, 2015, at 11:03 AM, Antonio Gonzalez <notifications@github.com>
wrote:

The issue is that some datasets (for example: the infant time series) the
most interesting field has unique values in all rows. However, this feature
is blocked by emperor. I can see two (3?) options: (1) We could open
completely via emperor, (2) as part of showing the summary of the biom table
<https://github.com/biocore/qiita/issues/1296> we allow the user to select
which categories to color by (then overwriting the not to color by unique
values, which is the default in emperor), or (3) both.

cc - @rob-knight <https://github.com/rob-knight> and @RNAer
<https://github.com/RNAer>

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1465>.

**Comment by antgonza** [comment]
This was solved in Emperor via Q2 so no longer an issue. Long live the Emperor!

**Comment by RNAer** [comment]
cool!

On Wed, Oct 11, 2017 at 10:10 AM, Antonio Gonzalez <notifications@github.com
