### ISSUE TITLE
Changes suggested for update sample template

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1591]
The update/add functionality needs some work to improve use-ability.  (Not sure if this will be fixed by new working page GUI.)
Problems:
1.  If you add samples to a template there are different options: add only the new samples without changing anything in existing template; update existing template without adding new samples; if you need to do both of these because you notice problems with existing template (very common) you may have a horrible template that has duplicated samples, some of them prepended twice with study ID;
2.  If the last situation occurs there is no way to step back to the last acceptable version of the template - mentioned in another issue (1589).
3. I think documentation has to reflect these current problems or we need to fix.

**Comment by antgonza** [comment]
I think the best solution is to fix them.

**Comment by ackermag** [comment]
Still an issue

**Comment by antgonza** [comment]
Summarizing: the issue is that the validate performs the prefix check in all the samples and if the new template has both new (not prefixed) and old samples (prefixed) it will add all as new samples. 

Solution: Two fold. The system should be smarter by doing by-sample checks vs. bulk; and allow deletion of samples.

**Comment by antgonza** [comment]
https://github.com/biocore/qiita/pull/2370
