### ISSUE TITLE
Should any user with access to a study be able to share the study?

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1611]
Currently, the only one who can share the study is the owner of the study. Do we want to keep it like that or whoever who has access to the study can share the study? As an example, Bob owns a study and she shares it with Alice. Now Alice want to give me access to such study. Should Alice be able to give access or should Alice contact Bob so he can share the study with me?

**Comment by ackermag** [comment]
I am not sure that everyone who has access to a study should be able to share access...  Example - Cathy Lozupone has access to unpublished data from Jeff Gordon's lab and has asked that I share with people she works with (grad student, lab person).  Cathy asked Jeff for special permission to use his data and then me to share with the people working with her.  I think study owner (in this case me) should be able to determine if anyone else should have access, rather than an eternal list of people stemming from Cathy ad infinitum.  I think we have to be somewhat careful with this - especially with unpublished data.

**Comment by antgonza** [comment]
I think it makes sense what both @josenavas and @ackermag are saying. However, I believe we can't "protect" something that doesn't belong to us. IMOO if someone is sharing something with somebody else, they are doing it with all responsibility. For example, if JG sent the data to CL via email, what stops CL to share it with somebody else?

**Comment by rob-knight** [comment]
Most systems e.g. Google docs assume that if you have access, you also have privileges to share etc. This has to be the user’s responsibility not ours.

**Comment by josenavas** [comment]
Thanks for the input! I think we can move forward by using the model of moving that responsibility to the user.
