### ISSUE TITLE
Zero samples bug

### ISSUE THREAD

**Issue by Lavariot** [biocore/qiita#1613]
There are many zeros in the number of samples of studies that actually have samples. Example: https://qiita.ucsd.edu/study/description/10196
Thanks in advance, Puravida.

Álvaro Vega Hidalgo

**Comment by antgonza** [comment]
Just to be clear, the original issue was discovered in the study listing:

<img width="836" alt="screen shot 2016-01-20 at 3 14 19 pm" src="https://cloud.githubusercontent.com/assets/2014559/12464888/a224cec2-bf88-11e5-9319-96444b038ec7.png">

However, this also shows in the study summary page.

**Comment by josenavas** [comment]
Just to add more information to the issue and best way to solve it. We are currently storing that information in the database as a column in the study object. However, we should not be storing that number and just check the number of samples in the sample template, so those two numbers go out of sync (which is what is happening right now, since the study table is never updated)
