### ISSUE TITLE
Reference given as id, not name

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1748]
In the workflow creator, the reference used is shown as the ID instead of the name and version number.

![image001](https://cloud.githubusercontent.com/assets/3079066/14288533/f0801856-fb0b-11e5-841f-875ee9943f7d.jpg)

**Comment by ElDeveloper** [comment]
I don't think this is an `easy-fix`. The way this information is processed, is by first getting a set of parameters with three attributes each, an `id`, a `name` and a `value`. In this case the representation is correct as the `value` for reference is indeed 1. If we wanted to fix this, we need to special-case [`list_options_handler_get_req`](https://github.com/biocore/qiita/blob/master/qiita_pet/handlers/api_proxy/processing.py#L72-L95) to check if the command is an OTU picking command and if the value to be presented is the reference. Is this accurate or am I missing something @josenavas?

Alternatively we could have the parameter of the command be the name of the reference instead of the identifier, but that sounds like a bad solution.

**Comment by josenavas** [comment]
You're right @ElDeveloper - the "easy-fix" will be hard-coding something which I disagree. One of the things that you may need to discuss is how to represent references in the system. Right now they're a special table and object, but we may want to change them to be just a special artifact that is not attached to a prep template or to another artifact, but instead attached to a given plugin, since in this case this is a special type of artifact that a plugin creates. What do you think?

**Comment by ElDeveloper** [comment]
That kinda makes sense (re references as artifacts). Would probably be
better to discuss this in person, as I'm unsure what we would need to do
to achieve this.

**Comment by josenavas** [comment]
Sounds good!

**Comment by antgonza** [comment]
Should we move to the next milestone?

**Comment by ElDeveloper** [comment]
That sounds good to me.

**Comment by antgonza** [comment]
Resolution: references should with not be artifacts. Change the commands to have the file path of the references. Deprecate the reference table.

**Comment by antgonza** [comment]
This is still relevant as we haven't (TODO) deprecated the reference tables.

**Comment by antgonza** [comment]
This is no longer an issue since we moved all the system to use full paths vs. a database.
