### ISSUE TITLE
meta-analysis: cannot view emp PCoA through Qiita, must upload html file to view

### ISSUE THREAD

**Issue by jminich444** [biocore/qiita#1788]
I recently tried to do a meta-analysis with approximately 2000 samples from 7 studies in Qiita, rarifying to 5000 which dropped the samples down to 1500. The analysis completed and while I was able to view the alpha diversity plots, I got an error message when attempting to view the unweighted and weighted unifrac plots via emperor in Qiita. I followed the WebGPL protocols for safari and chrome but still could not view the plots Yoshiki was able to pull the html file from the Qiita tgz output file and successfully view in safari. Lastly, when I tried to view the barplots, Qiita crashes.
![screen shot 2016-04-14 at 12 39 04 pm](https://cloud.githubusercontent.com/assets/18352435/14541481/07895726-023f-11e6-8177-ebe7637c49bf.png)

**Comment by antgonza** [comment]
This is an issue with Emperor and your Internet browser. Do you have a recent version of Chrome or Safari?

**Comment by ElDeveloper** [comment]
@antgonza There's something off though, the file loaded from inside Qiita should display correctly, the screenshot seems to indicate that the resources were not loading correctly, otherwise you should have been able to see a differently formatted message with the logo, etc.

Opening the plot in Safari works, but not in Chrome, likely due to the Chrome version being out of date (still being a 32-bit version).

**Comment by jminich444** [comment]
Safari: Version 9.0.3 (9537.86.4.4)
Chrome: Version 49.0.2623.112 (64-bit)


[image: Inline image 1]

On Thu, Apr 14, 2016 at 12:48 PM, Antonio Gonzalez <notifications@github.com

**Comment by antgonza** [comment]
Thanks for sending and you guys are right, checking the system.

**Comment by ElDeveloper** [comment]
Wow, that's odd ... it's a 64-bit version  `¯\_(ツ)_/¯`

**Comment by josenavas** [comment]
We found the issue - it was a problem with the nginx configuration. Thanks for reporting the issue!
