### ISSUE TITLE
Missing moi installation instructions on the install page

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1863]
In the current install instructions, the release version of moi is installed. However, we should be installing the development version of moi, so it is missing this command before installing Qiita:
``` bash
pip install https://github.com/biocore/mustached-octo-ironman/archive/master.zip --no-deps
```

@HannesHolste can you fix?

**Comment by HannesHolste** [comment]
Good catch – I tested it with the release version moi originally, but is it better to use the moi dev version because it's more up to date than the release version, or because of something else?

Right now `moi` is listed under `install_requires` in `setup.py`.  I think I struggled with trying to get it to prefer the `moi-dev` version in `setup.py`. So can I completely remove moi from this?:
```python
install_requires=['psycopg2', 'click >= 3.3', 'future',
                        'bcrypt', 'pandas >= 0.17', 'numpy >= 1.7',
                        'tornado==3.1.1', 'toredis', 'redis', 'six',
                        'ipython[all] >= 2.4.1, < 2.5', 'pyparsing',
                        'h5py >= 2.3.1', 'biom-format', 'natsort', 'networkx',
                        'scikit-bio >= 0.2.3, < 0.3.0', 'wtforms == 2.0.1',
                        'qiime >= 1.9.0, < 1.10.0', 'moi',
                        'sphinx-bootstrap-theme', 'Sphinx >= 1.2.2',
                        'gitpython'],
```

**Comment by josenavas** [comment]
There are a couple of small fixes that were introduced in the dev version.

No, don't remove moi from that list. install_requires should list all the packages that Qiita depends on. Once we do an actual release of Qiita we will also do a release of moi.

**Comment by antgonza** [comment]
Fixed in https://github.com/biocore/qiita/pull/1864
