### ISSUE TITLE
Select Samples for EBI submission by Sample Metadata

### ISSUE THREAD

**Issue by jwdebelius** [biocore/qiita#1870]
It would be helpful if a list of samples (or maybe samples filtered by metadata category) could be uploaded to EBI from a single study, rather than having separate prep templates. 

The use case occurs happens when you have multiple experiments from the same collaborator on a single run, or you determine that you want to treat a set of data as multiple experiments for the sake of publication, even though it's the same type of data. (i.e. I have a sequencing run of 16S samples from one collaborator, and we're submitting a manuscript on a subset of the samples now, and would like to write a manuscript on another subset later).
This use case has come up twice in the past couple of months.

Currently, I believe that I need to download all of the current Qiita artifacts, delete them out of Qiita, split the prep template into two files based on my experimental designation (a column in my sample metadata), re-upload my two prep templates, and reprocess the data prior to EBI submission.

**Comment by antgonza** [comment]
Good idea and it should be possible. However, not sure if that will be the right solution for your use case. The problem comes from EBI itself. Each study can only have 1 accession number so if you want to publish one single sequencing run as 2 different projects/papers and want to have different accessions for each study, you will need to create 2 different studies, not prep info files within the same study.

Remember the AGP, one single study accession and multiple depositions.

**Comment by antgonza** [comment]
Closing as:
- If you need multiple study accessions you should create multiple studies
- If you require multiple preps you should create multiple preps
Note that this is what we are currently doing.
