### ISSUE TITLE
firefox compatibility 

### ISSUE THREAD

**Issue by dridk** [biocore/qiita#1911]
I get this message when I use the last version of firefox. I wonder which features chrome support and firefox not. 

![pipeline1](https://cloud.githubusercontent.com/assets/1911063/17435406/eb5df806-5b10-11e6-916c-e91defab8224.png)

**Comment by antgonza** [comment]
That's an excellent question. In a previous workshop we realized that each OS has different versions of browsers and each of them support different things; thus, decided that we should only support one  browser as having different ones is pretty hard and time consuming. 

We decided that Chrome was the best one to support based on other tool we use, like Emperor and Ili.

This issue is related to: https://github.com/biocore/qiita/issues/1868

**Comment by rob-knight** [comment]
I don’t think this is a reasonable solution to the problem. While it’s ok to support one browser while the UI is undergoing rapid development, having only one browser supported will greatly limit the user community, especially among the less technical users who are our main target audience. So the message should clearly note that this is a temporary phase while in the current stage of development.

Obviously we can’t support every browser out there, but just supporting the most recent version of one browser is too limited.

On Aug 14, 2016, at 10:56 PM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>> wrote:


That's an excellent question. In a previous workshop we realized that each OS has different versions of browsers and each of them support different things; thus, decided that we should only support one browser as having different ones is pretty hard and time consuming.

We decided that Chrome was the best one to support based on other tool we use, like Emperor and Ili.

This issue is related to: #1868<https://github.com/biocore/qiita/issues/1868>

**Comment by qiyunzhu** [comment]
Deal all, I managed to access Qiita using my Firefox, which has a "user agent" to trick Qiita to believe that it is Chrome. I played with many Qiita functionalities. So far, I haven't experienced any issues, nor there are instances that elements are displayed differently in Firefox than in Chrome.

**Comment by antgonza** [comment]
Cool, which version of Firefox are you using?

**Comment by qiyunzhu** [comment]
It is Firefox 48.0.1. Like Chrome, Firefox by default always updates itself to the latest version. I instructed it to mimic Chrome 51 :)

**Comment by antgonza** [comment]
Got it, thanks. 

I just checked and it seems like Firefox releases their latests version to all operating systems. Just FYI, Chrome doesn't do that. For example, for XP, you can download the latests version of Firefox if you have SP3 by downloading an older version and then setting the auto install flag. Chrome doesn't go any further than v50. With this in mind it sounds like we could allow Firefox 48 and newer, right?

Any opposition?

**Comment by qiyunzhu** [comment]
Sounds good! I think Firefox 48 can be white-listed for now. I noticed that in some old systems (e.g., Mac OS 10.5.8), Chrome and/or Firefox won't upgrade to the latest version. I have Windows 3.11 to 8.1 (but not 10) and lots of Ubuntu versions. I can test Qiita of them if desired.

**Comment by antgonza** [comment]
Testing on Ubuntu: that will be great! And more if you can tests using the latests QIIME VM

**Comment by antgonza** [comment]
@qiyunzhu, don't forget to close this issue once you update https://github.com/biocore/qiita/pull/1922. Thanks!

**Comment by qiyunzhu** [comment]
Thanks for closing! Sorry I didn't notice this. - Qiyun
