### ISSUE TITLE
When you click on DOI it often fails to show publication

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1993]
I think it may be when I add doi  ref - not sure what format is correct and how to ensure it is accurate. e.g. Study ID 10243 is correct, others are not e.g. 10105 with doi and pmid.
Also pmid reported as 20231444 rather than pmid 20231444 will refer to DOI with error.

**Comment by ackermag** [comment]
We may also need to update the tutorial.

**Comment by jwdebelius** [comment]
:+1: on this issue

**Comment by ackermag** [comment]
In study ID:1772 when I click the link:
![screen shot 2016-11-29 at 12 07 53 pm](https://cloud.githubusercontent.com/assets/2014592/20809564/477a4a20-b7bb-11e6-8025-bab3cd93d9b4.png)
I get this:
![screen shot 2016-11-29 at 12 07 44 pm](https://cloud.githubusercontent.com/assets/2014592/20809571/512e6114-b7bb-11e6-97e9-2950cf17c9a1.png)

**Comment by ackermag** [comment]
sorry wrong pics:
![screen shot 2016-11-29 at 12 07 53 pm](https://cloud.githubusercontent.com/assets/2014592/20809645/905a7f58-b7bb-11e6-9fe3-5fda46c6d4e2.png)
![screen shot 2016-11-29 at 12 07 44 pm](https://cloud.githubusercontent.com/assets/2014592/20809644/90575db4-b7bb-11e6-80b2-72954df47779.png)

**Comment by antgonza** [comment]
So the issues come from the decision we made of only supporting (A) DOI and (B) users adding "DOI:" or other things to the id so the automatic links do not work. For (A), after chatting with @ackermag, we think the best will be to allow a list of DOIs and pubmed ids for each study, separated by commas. For (B) better documentation should suffice. 

The plan is to add pubmed ids as a field in the study create/edit, where we explain that comma separated links and allow a bunch of unrelated values -- currently, we expect a doi/pubmedis pair. 

I'll start working on this tomorrow morning if I don't hear otherwise.

**Comment by rob-knight** [comment]
Sounds good

On Dec 1, 2016, at 2:41 PM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>> wrote:


So the issues come from the decision we made of only supporting (A) DOI and (B) users adding "DOI:" or other things to the id so the automatic links do not work. For (A), after chatting with @ackermag<https://github.com/ackermag>, we think the best will be to allow a list of DOIs and pubmed ids for each study, separated by commas. For (B) better documentation should suffice.

The plan is to add pubmed ids as a field in the study create/edit, where we explain that comma separated links and allow a bunch of unrelated values -- currently, we expect a doi/pubmedis pair.

I'll start working on this tomorrow morning if I don't hear otherwise.

-
