### ISSUE TITLE
Long file names are cut in the tooltip

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#2084]
See below:

![screen shot 2017-02-25 at 12 15 54 pm](https://cloud.githubusercontent.com/assets/2501478/23367282/8fbd0df2-fcbe-11e6-9871-a87a1c7fbb34.png)

**Comment by ackermag** [comment]
Long file names are still being cut which makes ensuring that the correct file is assigned as barcodes, forward and reverse run sometimes difficult.  Is it possible to have the text in the hover-over-window wrap instead of end in '....'?  As far as I understand it the files are assigned alphabetically by qiita not logically

**Comment by antgonza** [comment]
fixed in https://github.com/biocore/qiita/pull/2365
