### ISSUE TITLE
After starting EBi submission the status on the study page stays as "not submitted"

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2321]
Should show as "submitting" on study page and have a banner message with job number (EBI submission started. Job id: 6d87cd26-9c1d-4f26-9173-b2c580325c57)

**Comment by antgonza** [comment]
Yup, confirmed. My _guess_ is that as the jobs run in a transaction the status doesn't get updated in the DB. @josenavas, what do you think?

**Comment by josenavas** [comment]
Yes, my guess is that this is a result of running it in a separate transaction through the internal plugin system. I think a good solution would be to change the attribute so that instead of being stored in the DB as "submitted", "submitting" or "not submitted" it is inferred by the existence of the EBI accession number and the existence of an active job submitting to EBI

**Comment by antgonza** [comment]
Closed by: https://github.com/biocore/qiita/pull/2522
