### ISSUE TITLE
Upload Files page: uploading file with same name and refreshing causes failure

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2335]
Steps to reproduce:
Upload file "metadata.txt"
Navigate to another page
Return to Upload Files page
Select  "metadata.txt" and delete it [user realized it was the wrong one or received an error when trying to associate it]
Upload new "metadata.txt"
Refresh page with browser button to make sure it 'took' [and because so far we train users to constantly refresh)
Click yes to warning
File does not appear and has not been uploaded.

**Comment by antgonza** [comment]
Related to: https://github.com/biocore/qiita/issues/2334 but even more interesting. What's happening is that the user:
1. uploads a file - goes and comes back
2. deletes that file (BTW another option is to over write it)
3. uploads file
4. refreshes page, accepts message (note that the last actual refresh was to delete), the page deletes the file.

I think the actual source of this issue is a user not being sure if their file was actually uploaded and I _think_ in the new interfase it was solved by an upload icon (while uploading) and a check (when done), see:
![upload](https://user-images.githubusercontent.com/2014559/34838032-e10c3b60-f6b9-11e7-8bcd-bdd042aeaf22.gif)

Thus, closing.
