### ISSUE TITLE
Roundtripping sequencing files does not work

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2347]
Steps to reproduce:
Download raw sequencing files (fastq), metadata, and prep info from study 1
Delete irrelevant samples/samples not of interest from metadata and prep info file
Create study 2
Upload revised metadata, prep info, and unchanged fastq files
Create new prep and associate fastq files
Attempt to demux fastq files
Receive error that demux-ing is not possible

I suspect Qiita expects fastqz and these files are fastq, though if that is the case we should make it accept both, document well that it wants fastqz and not fastq, and/or make the download buttons download .fastqz instead of .fastq

To be fair this current example at the top is only currently necessary (may in fact discourage later for data duplication reasons), because it is not possible to filter samples without losing taxonomy in the current Q2/Q2 plugin.

**Comment by josenavas** [comment]
Agree that we should take a look at that - however I also want to point out that if they're the exact same files you don't need to download them and upload them again. On the page to create the first artifact, you can import an artifact from another study instead of uploading the files:

<img width="1850" alt="screen shot 2017-10-12 at 6 18 49 pm" src="https://user-images.githubusercontent.com/2501478/31526175-038377f8-af7a-11e7-96ab-b0e1124b2e27.png">

**Comment by josenavas** [comment]
Right now is possible to filter samples without loosing taxonomy. The system also allows importing the artifacts from another study so no need to download and upload again.
