### ISSUE TITLE
forbidden column names in sample information

### ISSUE THREAD

**Issue by tkosciol** [biocore/qiita#2553]
some column names, e.g. "BarcodeSequence", "LinkerPrimerSequence" shouldn't be allowed in sample information files.
They may cause downstream errors due to conflicts with column names in preparation information.

**Comment by antgonza** [comment]
This issue is related to: https://github.com/biocore/qiita/issues/2628.

During Qiita meeting we decided to not allow in Sample Information File:
- if there is a prep do not allow any of the columns (I think it's there but not sure)
- if new: BarcodeSequence, LinkerPrimerSequence, barcode, linker, primer, and run_prefix
