### ISSUE TITLE
Add a note for filtering

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2567]
I recently tried to filter for mother's own milk but it kept failing. Yoshiki and I tried it on Qiime2 and the command --p-where "type_of_feed_7_d = \"mother's own milk\"" worked. Add a note that to filter samples with an apostrophe in it you must write the command like type_of_feed_7_d = \"mother's own milk\". Not sure if you want me to add this in the help or tutorial or if you want to add this to the actual Qiita filtering command page but we should document it somewhere.

**Comment by stephanieorch** [comment]
That command is no longer working but it did work maybe a month ago.

Error in filtering samples in biom Std out: Std err: /bin/sh: -c: line 0: unexpected EOF while looking for matching `"' /bin/sh: -c: line 1: syntax error: unexpected end of file

**Comment by stephanieorch** [comment]
This is still an issue. I can't figure out how to filter for samples that contain metadata with an apostrophe in it.

**Comment by antgonza** [comment]
@stephanieorch, in your original post, you said:
"""Add a note that to filter samples with an apostrophe in it you must write the command like type_of_feed_7_d = "mother's own milk". Not sure if you want me to add this in the help or tutorial or if you want to add this to the actual Qiita filtering command page but we should document it somewhere."""
So, is that the solution or you are not sure?

Now, the problem with this issue is that this is a comment specific to a command so the best place to add it: the tutorials.

**Comment by stephanieorch** [comment]
It worked at one point but now it doesn't work. Not sure what happened... So there is currently no solution to this.

**Comment by antgonza** [comment]
That's weird, when was the last time you checked? Is that analysis still avaialble?

**Comment by stephanieorch** [comment]
I checked it today and it didn't work. I keep getting the error that I posted above on May 17th... I can't find the original job that worked.

**Comment by stephanieorch** [comment]
Just added this to the CMI tutorial under filtering

**Comment by antgonza** [comment]
@stephanieorch, can we close?

**Comment by stephanieorch** [comment]
Yes. But remember that it's not in the help documentation, only in the tutorial
