### ISSUE TITLE
Error: Code 500! should give incorrect password error instead

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2579]
A user just got this error:

![error](https://user-images.githubusercontent.com/31080457/39585537-e6013fe2-4ea9-11e8-86c5-0eeb9281bf02.png)

When Antonio looked at, the error should be saying something along the lines of IncorrectPasswordError("Bad password given!") instead.

**Comment by stephanieorch** [comment]
Along with this: when you create a password with special characters you get a message saying your password isn't verified rather than getting a "special characters can't be used" error.

**Comment by charles-cowart** [comment]
Just to confirm, the cause of the above screenshot is a user entering a password with special characters in it? Or is the special characters case in addition to whatever caused the above screenshot?

**Comment by stephanieorch** [comment]
When the user tried to make an account, he received the screenshotted error. To fix this, he just had to input a different password that didn't contain special characters. 
So: Replate "ERROR: CODE 500!" with something like "Error: Passwords cannot contain special characters".

**Comment by antgonza** [comment]
Just to confirm, the current html doesn't show the password requirements/restrictions and the error doesn't tell you about this and give you the chance to try again ...

**Comment by stephanieorch** [comment]
Yes

**Comment by charles-cowart** [comment]
Just to reiterate, the 500 error is caused because the server side is expecting valid inputs for password & confirm_password; error-handling appears to be performed entirely on the client-side. What I've done is add a custom handler (as in, not a JQuery rule) to validate that the password only contains printable ASCII characters (no UTF-8).

This should prevent the user from ever seeing the above 500 error; instead the user will need to correct their input before they can submit their query. If we'd still like to add server-side parameter checking for this option, I would recommend changing the status code from 500 to 400 (bad parameter) or 422 (unprocessable entity).

![password](https://user-images.githubusercontent.com/42684307/45114295-7755de80-b101-11e8-8055-dc82c24f9bba.gif)

**Comment by antgonza** [comment]
Fixed: https://github.com/biocore/qiita/pull/2659
