### ISSUE TITLE
Improve sample deletion

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2623]
Users can currently delete samples from their metadata with one click of the trash button without any confirmation or warning, and this is the only way to remove unwanted samples. 

It would be preferable to have checkboxes so multiple samples could be deleted at once but with a pop-up confirmation before deleting the samples, ideally with a list of the samples to be deleted so that the user can confirm this action.

**Comment by antgonza** [comment]
This is an intentional design, so users cannot remove lots of samples at once. If there are lots of samples to be remove, it might be easier to just remove the full sample info file. Anyway, I can see the desirability of deleting multiple samples; let's bring it up in the next qiita meeting. 

BTW this is a GUI and backend change; AKA not super easy but neither hard.

**Comment by adswafford** [comment]
Discussing at the next meeting sounds good because removing the full sample info file isn't possible once any of the samples in it have been processed. This has resulted in a few studies needing to be duplicated to resolve an upload error.

**Comment by adswafford** [comment]
Based on feedback at Qiita meeting:
add sort to table
add option to delete all samples not associated with a prep

**Comment by stephanieorch** [comment]
I was asked at the Qiita meeting held on 8/29/18 to label issues I find crucial as "must-have". I am unable to add a label but I believe this is a must-have.
