### ISSUE TITLE
Add QIIME2-Qiita how to tutorial to FAQ

### ISSUE THREAD

**Issue by afvrbanac** [biocore/qiita#2700]
The "rejected fragments" appear to be missing from the final tree, but still appear in the deblur feature table. This means when you attempt to use this Qiita-generated tree and deblur feature table with qiime 2, the following error message will be generated since the feature table contains sequences which are not present in the tree:
"All ``feature_ids`` must be present as tip names in ``phylogeny``. ``feature_ids`` not corresponding to tip names"

I've never had this issue with trees generated by the q2-fragment insertion plugin, just the ones from Qiita.

**Comment by antgonza** [comment]
The reason this is happening is because by default the q2-deblur/deblur plugin removes any features that are found less than 10 times and doesn't produce a non-filtered output (all features); however, in Qiita we leave this parameter as it can be helpful to see if we can find those "rare" features in other studies and the non-filtered as you can use deblur on other than 16S. Also, note that fragment insertion actually expects this and have a method to [remove them automatically](https://github.com/biocore/q2-fragment-insertion#filter-feature-tables), and is part of the [Qiime2-Qiita forum how to](https://forum.qiime2.org/t/transferring-qiita-artifacts-to-qiime2/4790). 

As you can see, this is broadly explained in the documentation of the tools but understand that can be confusing, we could add this explanation to the FAQ, what do you think?

**Comment by afvrbanac** [comment]
Interesting, I must just have an old version of q2-fragment insertion installed that doesn't do this. I think it would be much more clear when/if q2-fragment insertion is integrated into the primary q2 documentation. I've just had a couple of new students ask "why don't the trees from Qiita work", so it seems the documentation of this issue may not be readily apparent. Now I know there is a nice Qiime2-Qiita tutorial I can send people! It would be great to have that tutorial in the main Qiime2 documentation too, but I understand if the Q2 devs don't want to...maybe worth adding to the Qiita documentation or FAQ?

**Comment by antgonza** [comment]
1. We are working on having fragment insertion be part of the [main documentation and tutorials](https://github.com/qiime2/docs/blob/fmt_cdiff/source/tutorials/fmt-cdiff.rst)
2. Adding a link to that tutorial from the FMT seems reasonable, will rename the issue
