### ISSUE TITLE
Add a user interruption (banner, popup, etc.) that reminds users not to upload data with human reads to Qiita

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2763]

**Comment by antgonza** [comment]
Can you add the exact text you think will work? We'll add in the upload page ...

**Comment by adswafford** [comment]
"Per our Terms of Condition for use, you certify that the files you are uploading do not contain
1) protected health information within the meaning of 45 Code of Federal Regulations part 160 and part 164, subparts A and E; see checklist here: https://drive.google.com/a/eng.ucsd.edu/file/d/0B6NwNax2VIfab1lBWmVQSGdnM0U/
2) whole genome sequencing data for any human subject; HMP human sequence removal protocol: https://www.hmpdacc.org/hmp/doc/HumanSequenceRemoval_SOP.pdf
3) any Data that is copyrighted, protected by trade secret, or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from the rightful owner(s) to transfer the Data and grant Qiita, on behalf of the Regents of the University of California, all of the license rights granted in our Terms. https://qiita.ucsd.edu/iframe/?iframe=qiita-terms

**Comment by adswafford** [comment]
Make the urls hyperlinked from words rather than the full url of course

**Comment by antgonza** [comment]
I would not suggest a popup as it will add extra clicks to the interface; however, we could add as part of the upload page. I think either on the pink or red boxes:
<img width="1232" alt="2763" src="https://user-images.githubusercontent.com/2014559/50484321-18b4b900-09ad-11e9-8233-328e43c7ea42.png"> 
I think pink makes sense. 

Now, this points to the HMP SOP, which is fine but not what we will be doing for our own sequences so should we add one/both?

**Comment by adswafford** [comment]
While the risk of annoying people with extra clicks is reasonable, the
danger of having human reads on our servers, even if we tell people not to,
is also reasonable. Suggest we come to a consensus at the next Qiitameeting
on the balance? Relatedly, finally revamping the upload to happen on
multiple pages, e.g. having an upload box for prep and sample.info, being
able to select single files via dropdowns, etc. would mititgste the extra
clicks since you'd only be asked to certify it on the upload of sequences
rather than for every metadata update.

**Comment by adswafford** [comment]
Here is the new clean CMI PHI link: 
http://cmi.ucsd.edu/PHIChecklist

**Comment by antgonza** [comment]
@adswafford and I just agreed on:
Per our Terms of Condition for use, you certify that the files you are uploading do not contain
1) protected health information within the meaning of 45 Code of Federal Regulations part 160 and part 164, subparts A and E; see checklist here: http://cmi.ucsd.edu/PHIChecklist.
2) whole genome sequencing data for any human subject; HMP human sequence removal protocol: https://www.hmpdacc.org/hmp/doc/HumanSequenceRemoval_SOP.pdf
3) any Data that is copyrighted, protected by trade secret, or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from the rightful owner(s) to transfer the Data and grant Qiita, on behalf of the Regents of the University of California, all of the license rights granted in our Terms. https://qiita.ucsd.edu/iframe/?iframe=qiita-terms
