### ISSUE TITLE
Add instructions for using PostgreSQL 9.5 installed via Homebrew

### ISSUE THREAD

**Issue by charles-cowart** [biocore/qiita#2832]
To support a commonly used method to install PostgreSQL on MacOSX.

**Comment by antgonza** [comment]
@charles-cowart, just to confirm, this issue is to add [this line](https://stackoverflow.com/a/44235570) somewhere in the documentation, right?

**Comment by charles-cowart** [comment]
I would work more from https://medium.com/@Umesh_Kafle/postgresql-and-postgis-installation-in-mac-os-87fa98a6814d as an example, just because (if you haven't done it before), starting up with pg_ctrl, initializing a database with initdb, and set the service to start on boot w/launchd (brew services start postgresql) are also important.

**Comment by charles-cowart** [comment]
Happy to do this, if you need.

**Comment by antgonza** [comment]
Got it, the [current instructions](https://github.com/biocore/qiita/blob/dev/INSTALL.md#postgresql-installation-on-mac-os-x) suggest using Postgres.app, which does all that for you for free! Anyway, what about just linking that document?

**Comment by charles-cowart** [comment]
The blog post? That doesn't sound like a good idea. I can add a few lines, it's no trouble.

**Comment by antgonza** [comment]
Yup, the blog post. Anyway, assigning to you and if you use those instructions are a reference, please don't forget to cite ...

**Comment by antgonza** [comment]
We currently have detailed instructions for the [Postgres.app](https://postgresapp.com/downloads.html), which works just fine. If a dev wants to install using any other methods: installing from source, homebrew, apt-get, etc, it's because that's what they normally use so the need for detailed instructions on those other methods is not required; and perhaps impossible to cover them all. However, we welcome any improvements to the documentation so if you want to add it, please do so! Thank you @charles-cowart.
