### ISSUE TITLE
scp upload, key file error

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2998]
I am trying to use the scp function to upload file. Using my public key results in a red error message ending with `paramiko.ssh_exception.SSHException: not a valid RSA private key file`, using the private key results in a popup `Your input file is too large to be a valid key, please try again.`

The file is of 3,2kb size. Is that too long? I think I used RSA 4096

**Comment by antgonza** [comment]
Yup, there is a limit of 2K for the file size of keys; which is easy to increase but wondering if it's actually needed? @sjanssen2 and @dhakim87, what do you think? 

@sjanssen2, a quick solution is to use a smaller RSA encryption.

**Comment by dhakim87** [comment]
We should increase the file size.  RSA 4096 is not a new standard and we shouldn't limit the ability to use it.  It is more secure than RSA 2048 but adds overhead of ~20 milliseconds to the initial handshaking on new connections.  It is slated to replace RSA 2048 entirely by the year 2030.  

Note that while the rsa key itself is 4096 bits (512 bytes), the private key file generated by `ssh-keygen -b 4096 -t rsa` will be around 3-3.5 kB due to the base64 encoding and the additional metadata stored about the key.

**Comment by antgonza** [comment]
Thank you @dhakim87, should we raise to 4K then?

**Comment by dhakim87** [comment]
I'm not sure how to judge the maximum file size an RSA 4096 private key can take up, but that looks to be a good amount of extra buffer from my own tests locally.  Note that the format includes additional metadata about the username and workstation as well as any free form comment the user wishes to add upon generation of the file, so I doubt there is a theoretical max size on the file itself.

**Comment by wasade** [comment]
Is the size limitation due to a database field? If so why not just change to `TEXT`?

**Comment by antgonza** [comment]
@wasade, it's a JS validation/limitation, my guess just to avoid users uploading their favorite video by mistake.

@dhakim87, just to confirm, anything we should do with the extra information? Just want to be sure I'm not missing anything.

**Comment by dhakim87** [comment]
I don't really know the context on this, but anything encoded in the file itself should be handled by whatever libraries are establishing the ssh session, it should be opaque to our code.

**Comment by antgonza** [comment]
K, will issue a PR fixing this so it can be included on Monday's deployment.
