### ISSUE TITLE
Alpha rarefaction curves - issue with 'Number of observed features..."

### ISSUE THREAD

**Issue by justinshaffer** [biocore/qiita#3038]
Hello,

When attempting to generate alpha rarefaction curves, I notice that when designating 'Number of observed features, including singles and doubles' the following error is generated:

Error running: Parameter 'metrics' received {'osd'} as an argument, which is incompatible with parameter type: Set[Str % Choices('faith_pd', 'fisher_alpha', 'doubles', 'menhinick', 'chao1', 'observed_features', 'michaelis_menten_fit', 'enspie', 'simpson_e', 'shannon', 'singles', 'dominance', 'gini_index', 'berger_parker_d', 'margalef', 'mcintosh_e', 'pielou_e', 'heip_e', 'goods_coverage', 'ace', 'robbins', 'lladser_pe', 'brillouin_d', 'simpson', 'mcintosh_d')]

... perhaps indicating this is no longer an option for the metric used.

You can see the error here, but note there are two failed artifacts so just be sure to check them both.

https://qiita.ucsd.edu/analysis/description/32263/

Thank you

**Comment by antgonza** [comment]
This is a good catch and an interesting issue that I discussed with the Q2 developers (thank you @thermokarst). The issue is that Qiita assumes that all alpha and alpha_phylogenetic metrics are present in alpha_rarefaction, which is not true (from qiime2.2020.08):
```
$ qiime diversity alpha-rarefaction --help
  --p-metrics TEXT... Choices('mcintosh_e', 'doubles', 'heip_e',
    'brillouin_d', 'faith_pd', 'berger_parker_d', 'menhinick', 'gini_index',
    'observed_features', 'ace', 'simpson_e', 'michaelis_menten_fit',
    'shannon', 'goods_coverage', 'lladser_pe', 'enspie', 'mcintosh_d',
    'dominance', 'simpson', 'chao1', 'singles', 'fisher_alpha', 'margalef',
    'pielou_e', 'robbins')
$ qiime diversity alpha --help
  --p-metric TEXT Choices('strong', 'mcintosh_e', 'doubles', 'heip_e',
    'brillouin_d', 'berger_parker_d', 'menhinick', 'gini_index',
    'observed_features', 'chao1_ci', 'ace', 'simpson_e',
    'michaelis_menten_fit', 'shannon', 'goods_coverage', 'lladser_pe',
    'enspie', 'mcintosh_d', 'dominance', 'simpson', 'chao1', 'singles',
    'fisher_alpha', 'osd', 'esty_ci', 'margalef', 'pielou_e', 'robbins',
    'kempton_taylor_q')
$ qiime diversity alpha-phylogenetic --help
  --p-metric TEXT         The alpha diversity metric to be computed.
    Choices('faith_pd')
```

Turns out that alpha rarefaction [specifically avoids some metrics](https://github.com/qiime2/q2-diversity/blob/c4dfefd916d91f7eb164d7edd62f7d2f2aee4906/q2_diversity/_alpha/_visualizer.py#L423-L425) so the solution is for Qiita to check for the specific metrics available for each method ...
