### ISSUE TITLE
EBI submission scripts should be able to source from the database

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#369]
Currently expect prep/sample templates to be files. Also need support for HDF5 demux

**Comment by adamrp** [comment]
To take this a step further, I think we should remove the ability to submit to EBI directly from files, and instead require that all information needed for an EBI submission be properly linked in the database. Note that the only reason it allowed submission from files in the first place was due to some urgent submissions that needed to go out before pertinent database code was in place.

**Comment by josenavas** [comment]
:+1:

**Comment by antgonza** [comment]
Fixed in #1451. Note that you still can submit from CLI but you can only pass the preprocessed_data_id, the action and if you really want to send.
