### ISSUE TITLE
Add ascp to travis to test EBI

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#406]
@adamrp mentioned that it would be nice to have this downloaded and installed in travis so we could do a test EBI submission, though note that we would need some test credentials of some sort.

**Comment by antgonza** [comment]
Update: We have now tests and ascp added to travis. Added to qiita_ware/tests/test_commands.py by https://github.com/biocore/qiita/pull/1488. However, tests to EBI can only be ran once because once a submission is created it will exists in the test server until the system is reset. EBI knows about this and is in their TODO list. Note that the tests are there except that are commented and have a pass.

**Comment by antgonza** [comment]
Update from EBI:

------------

Neil has added ROLLBACK submission action:
http://ftp.sra.ebi.ac.uk/meta/xsd/sra_1_5/SRA.submission.xsd

Please avoid using against the production service because accession numbers are assigned and lost.

------------


We should be able to fully test on merge to master and close this issue.

**Comment by antgonza** [comment]
Added and tested here: https://github.com/biocore/qiita/pull/2516
