### ISSUE TITLE
expand data shown on stats page

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#557]
Some things we might want to add:

- [ ] Number of (unique?) sequences
- [ ] Number of OTUs
- [ ] Number of biomes represented

**Comment by antgonza** [comment]
Removing easy-fix and milestone. The complexity of this issue is that currently we do not keep track of any of the sequences or OTUs statistics that were requested in the DB and to start displaying them we will need to:
- Have a patch that counts the number of seqs and otus in the hdf5 files
- Have a place to store them, perhaps the settings table?
- Display those values

Perhaps the counter can be part of https://github.com/biocore/qiita/issues/814

**Comment by antgonza** [comment]
I think this issue has been superseded by https://github.com/biocore/qiita/issues/1425. Open again if you think otherwise.
