### ISSUE TITLE
load_template_to_dataframe silently drops columns

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#740]
If they are all `NA`, see [here](https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template.py#L1748)

**Comment by ElDeveloper** [comment]
The reason why that happened is because pandas infers that `NA` should be considered an empty value and when we filter to remove empty data, these columns are removed. If you for example had used `no_data`, the columns would have been retained.

What do we actually want to do here? Keep the column but with empty values? We can also change the values that pandas infers as "empty" and remove NA, N/A, na as these are all commonly seen in metadata mapping files.

**Comment by antgonza** [comment]
I think we need to ignore the columns that have no column name and/or
only spaces as input in either the name and the values.

**Comment by ElDeveloper** [comment]
If I understand correctly, what we want to do is to ignore/remove:
- unnamed columns.
- columns where all values are an empty string.

So in general we don't want to infer empty values through pandas.

**Comment by antgonza** [comment]
I think that sounds reasonable.

**Comment by ElDeveloper** [comment]
Do we want to raise warnings of some sort?

**Comment by antgonza** [comment]
Also sounds reasonable, perhaps just a warning saying that the prep
template was added but X of columns where ignored due to being empty.
