### ISSUE TITLE
variable length barcodes

### ISSUE THREAD

**Issue by Mechah** [biocore/qiita#782]
Hey, due to some technical issues (see below) in the sequencing process our lab and our sequencing company uses barcodes with variable lengths in amplicon studies.
I realized QIITA currently supports only 8bp and 12bp barcodes. We use 7 to 10 bp barcodes!
So it would be a great help if QIITA would support variable length barcodes (as in the split lib QIIME script). As this script can be applied only for fasta and qual files it would be another great thing if split lib fastq in QIIME would support variable length barcodes as well.
As a first step it would help as well if QIITA supports different length of barcodes (e.g. 7-12 bp). Then maybe I could group my reads according to barcode length and then process them separately. Another  possibility would be to allow already demultiplexed data to be processed in QIITA...
Thanks for any help, adaptions or revisions.
Alex - Mechah
P.S. the reason why our lab and the sequencing company uses variable length barcodes is that we achieve higher data output. As Illumina has problems (sequencing is less efficient) with high similar reads - like in an 16S amplicon study - we increase sequence diversity not only via phiX DNA, but also with staggered barcodes of variable length so that the clusters in a flow cell are formed with different starting bases as the primers all have the same sequence...

**Comment by rob-knight** [comment]
We have found the value of this sequencing approach to be modest compared to the effort in deconvoluting the barcodes. This is therefore not a high priority for us relative to other tasks. We strongly recommend use of the EMP standard primer set.

Rob

On Jan 7, 2015, at 1:51 PM, Mechah <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, due to some technical issues (see below) in the sequencing process our lab and our sequencing company uses barcodes with variable lengths in amplicon studies.
I realized QIITA currently supports only 8bp and 12bp barcodes. We use 7 to 10 bp barcodes!
So it would be a great help if QIITA would support variable length barcodes (as in the split lib QIIME script). As this script can be applied only for fasta and qual files it would be another great thing if split lib fastq in QIIME would support variable length barcodes as well.
As a first step it would help as well if QIITA supports different length of barcodes (e.g. 7-12 bp). Then maybe I could group my reads according to barcode length and then process them separately. Another possibility would be to allow already demultiplexed data to be processed in QIITA...
Thanks for any help, adaptions or revisions.
Alex - Mechah
P.S. the reason why our lab and the sequencing company uses variable length barcodes is that we achieve higher data output. As Illumina has problems (sequencing is less efficient) with high similar reads - like in an 16S amplicon study - we increase sequence diversity not only via phiX DNA, but also with staggered barcodes of variable length so that the clusters in a flow cell are formed with different starting bases as the primers all have the same sequence...

**Comment by antgonza** [comment]
At this point adding new parameter sets is a simple insert into the DB, which get reflected immediately to the GUI user. Also, we already have added different strategies on qiita-mainsite based on specific request from users. Thus, closing this issue. If you want to have other preprocessing param sets, please verify that they haven't already been added and if not just add another issue with them. Thanks.

**Comment by ElDeveloper** [comment]
I don't think we have a way to process variable length barcodes in QIIME
i.e. I don't think there's a set of parameters in split libraries that
would be able to do this.

**Comment by antgonza** [comment]
Yes, we do, see barcode_type: http://qiime.org/scripts/split_libraries.html

**Comment by ElDeveloper** [comment]
This is not possible in `split_libraries_fastq.py` is it? From the help
file:

--barcode_type
The type of barcode used. This can be an integer, e.g. for length 6
barcodes, or golay_12 for golay error-correcting barcodes. Error
correction will only be applied for golay_12 barcodes. [default:
golay_12]

**Comment by antgonza** [comment]
Nop, this was added for those filetypes that rely on
split_libraries.py. Note that there are some hacks in qiime to make
this happen but not easy.

**Comment by ElDeveloper** [comment]
This text is in the opening comment of this issue:

As this script can be applied only for fasta and qual files it would be another great thing if split lib fastq in QIIME would support variable length barcodes as well.

**Comment by antgonza** [comment]
OK, that's an issue for qiime, right?

**Comment by ElDeveloper** [comment]
I would probably agree with that, except for the fact that the way to do
it in QIIME is to convert the FASTQs to FASTAs and then process using
split_libraries.py, not sure if we want to provide a way to streamline
this.

**Comment by adamrp** [comment]
@ElDeveloper That pipeline is also not ideal since the default parameters
(e.g., for quality filtering) in split_libraries.py are assuming a
completely different type of instrument (454). Users are probably not
considering those differences when they convert their illumina data to
fasta/qual and run it through split_libraries.py

**Comment by ElDeveloper** [comment]
Yes, that is a problem @walterst highlighted when I asked him about
this.  So I'm not sure what to do in this case. As a side note that this
issue was brought up at the UC Davis workshop.

**Comment by antgonza** [comment]
@ElDeveloper can we close this? I think we should as we agree that this is a limitation of qiime and not qiita, perhaps opening this issue in qiime will be better.

**Comment by ElDeveloper** [comment]
We discussed offline and agreed that since QIIME doesn't directly support this, we won't support this.

**Comment by antgonza** [comment]
... until qiime does.

**Comment by Mechah** [comment]
Too bad that this adjustment of the split_library_fastq script isn't an easy task...
I understand that this issue has to be solved in QIIME first before it is transferred to QIITA.
Hence, I accept that this topic is now closed on GitHub. Nevertheless, thanks for the discussion!
