### ISSUE TITLE
sample name in map and biom files

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#799]
if you upload a sample/prep template with upper case sample names the qiime mapping file that gets generated will keep them upper case but the biom table will have them lower case. This will block local analysis as the sample names do not match as all qiime/emperor/etc are case sensitive.

**Comment by antgonza** [comment]
Sorry, the other way around. The qiime mapping file will lower case everything but the biom will keep the casing.

**Comment by adamrp** [comment]
replicating one of my comments from #790 to keep track of this:

>I thought the plan here was to leave the sample names as they were when they were uploaded, and only add the study_id. prefix when doing a meta-analysis, to ensure that sample names are unique when multiple studies are being analyzed using the same prep/sample templates?

@antgonza pointed out that optionally including the study_id prefix would be good, since sometimes people want to download several templates for use in their own meta-analysis (i.e., a meta-analysis not run through the Qiita system), which I think would be best addressed by implementing the suggestion in the replicated comment above, and adding a checkbox that allows the user to explicitly select whether or not to prefix their sample IDs with the study ID (which could be checked by default, or not, depending on what the developers feel is most natural).

**Comment by ElDeveloper** [comment]
I agree with the idea of adding a checkbox.

**Comment by wasade** [comment]
:+1:

**Comment by antgonza** [comment]
Agree on checkbox, checked by default and add an alert message if the
user deselected as most of our users will have no idea what this
means. However, I still believe that it will be nice to have a simple
check: if all sample names have a prefix = [current study id]. avoid
the prefixing.

**Comment by wasade** [comment]
This should include a sanity check to make sure that if study IDs are not prefixed that the sample IDs are unique. If not unique, then a error message should pop
