### ISSUE TITLE
No list of algorithms for processing

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#808]
Currently there is no way of knowing what algorithms (sortmerna, uclust, etc) are available to the user by querying the database. This feature is needed to have complete user-controlled selection of processing options.

**Comment by antgonza** [comment]
@squirrelo has this been solved?

**Comment by squirrelo** [comment]
Not yet. The processing UI is still under construction, but should take care of this.

**Comment by josenavas** [comment]
Agree that this has not been solved, however I think the issue is more general that the one specified here. The issue should be about allowing the user to change any possible parameter for the given commands that can be run, but I think we agreed that at this point we are not going to allow this in our live system.

**Comment by antgonza** [comment]
This has been solved and superseded via the plugins and commands.
