### ISSUE TITLE
create automatic jobs

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#814]
This can be used to empty folders in the upload folder, check that the db and the file system are consistent, etc

From @squirrelo:
Looks like you want a combination of IOLoop.PeriodicCallback and IOLoop.add_timeout
http://stackoverflow.com/questions/24089086/unexpected-tornado-ioloop-periodiccallback-behavior

**Comment by antgonza** [comment]
It also should remove unused file paths.

**Comment by josenavas** [comment]
This issue is quite broad. We should better define which are the things that we want to do.

Also, IMOO we don't want to do this in the IOLoop, because that will be running on the server itself, so we are not freeing the main system of doing some work. Ideally this can be multiple cron jobs that start at `qiita webserver start` time.

**Comment by squirrelo** [comment]
We may be able to have two IOloops going, one for web server and one as a cron-type thing.

**Comment by josenavas** [comment]
Thanks @squirrelo 
But this means that the IOloop is still executed on the server machine right? I was thinking in something that is submitted to the queues and executed in a worker.

**Comment by antgonza** [comment]
Good point so perhaps an IOloop that starts a job in the workers is the way to go.

**Comment by wasade** [comment]
Yes, one of the motivations to make job submission as easy as possible with
moi, and without a need to tie it to a user
