### ISSUE TITLE
Add guide on how to start a development environment

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#82]

**Comment by squirrelo** [comment]
Is this taken care of by #902?

**Comment by ElDeveloper** [comment]
Yeah I think so.

**Comment by ElDeveloper** [comment]
#902 doesn't create a development environment, it creates a *release* environment.

**Comment by antgonza** [comment]
@ElDeveloper could you explain what's needed?

**Comment by ElDeveloper** [comment]
How to setup an environment from a git repository, creating an admin user (I believe this has to be done via the psql console), running the unit tests and I think that would be all.

**Comment by mortonjt** [comment]
While we're discussing this, I had one question.

Shouldn't the user be running `python setup.py build && python setup.py
install` in order to install qiita?  If so, the install docs will need to
be updated.

On a side note, I have a Docker image for qiita that is fairly close to
being complete.  This will also help automate this process.

**Comment by ElDeveloper** [comment]
I don't think so, using pip resolves dependencies and is the simplest
way to install a python package (I think).

YES, that would also work, though I think docker images make more sense
for live/production environments, we have a specific issue about this,
see: https://github.com/biocore/qiita/issues/1064

**Comment by ElDeveloper** [comment]
This has now be solved see, https://github.com/biocore/qiita/blob/master/INSTALL.md#install-qiita-development-version-and-its-python-dependencies
