### ISSUE TITLE
if a patch fails the settings should not be updated

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#849]
If a patch fails the settings get updated and you can not reapply the patch.

**Comment by wasade** [comment]
Was this happening on an intermediate patch or the terminal patch in a set of patches? I ask because the update to settings happens in a [queue](https://github.com/biocore/qiita/blob/master/qiita_db/environment_manager.py#L369), so the update shouldn't happen if an exception is thrown as it should teardown the queue. But, if the exception thrown isn't terminating the application of patches (in other words, failure on an intermediate patch) then this could happen I think.

@antgonza, if you've got a little more detail on this, I think I can resolve this quick

**Comment by antgonza** [comment]
I came across this when I was reviewing
https://github.com/biocore/qiita/pull/845 and found "The patch is not
working in my machine because the mountpoint has an ending / and the file
path doesn't" error. The patch failed but the settings table was updated.

**Comment by adamrp** [comment]
Ah yeah -- the SQL patch and the python patch are different steps. Although all the SQL is committed as a block, the python patch might fail. Not sure how to proceed here; the queue system might need an update, since the behavior we would like to implement will depend on isolation levels, if I'm not mistaken.

**Comment by adamrp** [comment]
Note that the settings table being updated is not a mistake -- the SQL patch was indeed applied successfully.

**Comment by wasade** [comment]
Okay, so to clarify, this issue is specific to python patches failing? I'm trying to figure out how to recreate this locally before attempting a fix

**Comment by antgonza** [comment]
It seems like that's the case.

**Comment by wasade** [comment]
Great, thanks

**Comment by wasade** [comment]
@adamrp, not sure if isolation level will work here as the python code will open its own unique connection. We'd have to rework the patches to get them to take the connection object for this to work, likely encapsulating them in methods, but I do not thing we should modify existing patches. Unfortunately, I think we may need to track sql and python patch level separately in the database.

**Comment by adamrp** [comment]
@wasade, I agree, that's probably the best route forward.

**Comment by josenavas** [comment]
This has been fixed with the transactions.
