### ISSUE TITLE
The study deletion issue

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#879]
Study deletion is tricky for many reasons, but we need to figure this out.

**Comment by ackermag** [comment]
I think we need to consider old studies where bugs still existed.  I don't
believe this will be an ongoing issue

On Fri, Feb 20, 2015 at 10:02 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> Study deletion is tricky for many reasons, but we need to figure this out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/879>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
This issue is related to: https://github.com/biocore/qiita/issues/596.

I have started working on deleting studies and I do not see it as
difficult because I think to be able to erase a study, you will need
to have no sample templates (not yet implemented), no prep templates
(implemented), etc. I think the most difficult one is to delete
process data as then we will need to figure out if there are part of a
(meta)analysis, if not fine to erase but if they are we could: allow
if not public, send emails to all people that use that meta-analysis
and flag it (add a message). Other option is to do all those steps,
except that we do not flag and erase those too (I do not like this
idea).

BTW, in the last update to the database, @josename and me, had to
clean all broke studies, sample and prep templates and now we have
queues to add these so we should _not_ have broken studies anymore.

What do you think?

**Comment by josenavas** [comment]
As @antgonza states, the trickiest step is removing processed data. This is becoming important and I'm going to start working on deleting ProcessedData, as it is needed for some of the EMP studies that we currently have on the DB. Thus, it will be great if we can have all the devs (ping! @biocore/qiita-dev ) commenting in here so we reach consensus and I can start working on it.

This is how I think it should work. Allow removal if and only if:
- The processed data is not public (we already decided that what we are going to publish are processed data, rather than studies).
- The processed data has not been used in any meta-analysis (we can then think on implementing meta-analysis removal).
- An admin can remove a processed data in any case, and then send an email to the users that have meta-analysis with such study (only needed in case that there are IRB problems)

What others think?

**Comment by antgonza** [comment]
Sounds fine except that I'm not sure we should erase all meta-analysis
(even by hand) that have used a certain about to be deleted processed
data vs. flagging them and make it clear in the GUI that this is the
case. What others think?

Also, just to confirm: currently we couldn't remove a processed data
that has been used in a meta-analysis as the DB will not allow it,
right?

**Comment by josenavas** [comment]
Yes, you're right, the DB will not allow it. Since we have #855 which aims to add a status to the processed data, we can add a new status such like "pending for removal" and we then flag all the meta-analysis that need to be removed. Here we can be more flexible: if there are IRB problems, we need to remove those meta-analysis immediately, if not, we can put some type of countdown: i.e this meta-analysis will be removed in 7 days.

**Comment by squirrelo** [comment]
Because of the `analysis_sample` table I think you are correct. We can't remove the processed data if it is used in an analysis. 

I agree with @josenavas implementation, although we do need a way for sandbox/private studies to be deleted even with analyses on them. I'm thinking we send an email to the users who used the study, and have a BIG RED BANNER that warns them on the analysis results page.

**Comment by adamrp** [comment]
Re: IRB concerns and removing things immediately, it might be a good idea to have yet another status, e.g., "Suppressed," where the data is no longer available/visible (except to admins), so that we can quickly suppress data without needing to go through the process of deleting it *immediately*.  This is similar to what EBI and other archives do.

**Comment by josenavas** [comment]
Assigning this to Alpha 0.2 as what is discussed here is how to delete studies that are public or with IRB concerns.

**Comment by antgonza** [comment]
the new analysis pipeline makes this more important as it also affects it

**Comment by antgonza** [comment]
Resolution: we will delete everything - only if everything in the study is sandboxed. If not possible to delete, list all things that are blocking deletion.

**Comment by antgonza** [comment]
This was solved in https://github.com/biocore/qiita/pull/2291
