### ISSUE TITLE
Alpha 0.1 Release Requirements

### ISSUE THREAD

**Issue by JWDebelius** [biocore/qiita#990]
**Release Story: Biologist can run the Illumina tutorial through Qiita (alpha diveristy, beta diversity, summary) or any other contingency table.**

The following were identified as steps along the way to that milestone, in the [hackpad](https://hackpad.com/Biocore-code-sprint-v15.3-X4ypG5V0mSz) document.

* [ ] Upload and parse a QIIME-compatable mapping file instead of a Sample Template and Prep Template.
* [ ] Upload a contingency table (biom table) which can be used for analysis with a non-phylogenetic metric.
* [ ] Process any target gene sequence (16s, 18s, ITS). Remove constraints around sequencing.
* [ ] Inpalce documentation on using [Keemai](https://github.com/jairideout/Keemei) to validate mapping files.
* [ ] Split libraries on target gene sequences
* [ ] Run Closed Reference OTU picking with multiple databases.
* [ ] Perform Core Diversity Analysis
* [ ] Perform meta-analysis combing two target gene data sets or any two uploaded contingency table.

**Comment by rob-knight** [comment]
Just to be clear, “summary” includes taxonomy yes? This is an essential component.

On Mar 16, 2015, at 11:10 AM, J W Debelius <notifications@github.com<mailto:notifications@github.com>> wrote:


Release Story: Biologist can run the Illumina tutorial through Qiita (alpha diveristy, beta diversity, summary) or any other contingency table.

The following were identified as steps along the way to that milestone, in the hackpad<https://hackpad.com/Biocore-code-sprint-v15.3-X4ypG5V0mSz> document.

 *    Upload and parse a QIIME-compatable mapping file instead of a Sample Template and Prep Template.
 *    Upload a contingency table (biom table) which can be used for analysis with a non-phylogenetic metric.
 *    Process any target gene sequence (16s, 18s, ITS). Remove constraints around sequencing.
 *    Inpalce documentation on using Keemai<https://github.com/jairideout/Keemei> to validate mapping files.
 *    Split libraries on target gene sequences
 *    Run Closed Reference OTU picking with multiple databases.
 *    Perform Core Diversity Analysis
 *    Perform meta-analysis combing two target gene data sets or any two uploaded contingency table.

**Comment by antgonza** [comment]
Yes, that's exactly what's implemented now.

**Comment by josenavas** [comment]
Closing in favor of #1084, #1085, #1086, #1087, #1088, #1089 and #1090
